---
- hosts: setup
#  accelerate: true
  vars_files:
    - base_vars.yml
  tasks:
  - name: install packages
    yum: name=$item state=present
    with_items:
      - gcc
      - gcc-c++
      - make
      - cmake
      - gtest
      - python-setuptools
      - gtest-devel
      - glog-devel
      - mysql-server
      - MySQL-python
      - mysql-connector-c++-devel
      - git
      - gcc
      - gcc-c++
      - make
      - wget #maybe unnecessary now with get_url
      - ntp
      - tar
      - bzip2-devel #for boost compile
      - python-devel #for boost compile
  - name: make sure jetstream deps dir exists
    file: dest=/jetstream/deps state=directory mode=777
  - name: download boost
    async: 180
    get_url: url=http://downloads.sourceforge.net/project/boost/boost/1.52.0/boost_1_52_0.tar.gz 
              dest=${js_deps}/boost_1_52_0.tar.gz 
  - name: untar boost
    async: 60
    command: tar -xzf boost_1_52_0.tar.gz
              chdir=/jetstream/deps
              creates=/jetstream/deps/boost_1_52_0
  - name: bootstrap boost
    command: ./bootstrap.sh 
              chdir=/jetstream/deps/boost_1_52_0
              creates=/jetstream/deps/boost_1_52_0/project-config.jam
  - name: b2 boost
    async: 600
    action: command ./b2
              chdir=/jetstream/deps/boost_1_52_0
              creates=/jetstream/deps/boost_1_52_0/stage/lib
     #async: 1000
     #poll: 10
     #include: /jetstream/deps/boost_1_52_0
     #lib: /jetstream/deps/boost_1_52_0/stage/lib
#mysql cpp connector
  - name: download mysql cpp conn
    async: 100
    get_url: url=http://dev.mysql.com/get/Downloads/Connector-C++/mysql-connector-c++-1.1.1-linux-glibc2.3-x86-64bit.tar.gz/from/http://cdn.mysql.com/
            dest=${js_deps}/mysql-connector-c++-1.1.1-linux-glibc2.3-x86-64bit.tar.gz
  - name: untar mysql cpp conn
    command: tar -xzf mysql-connector-c++-1.1.1-linux-glibc2.3-x86-64bit.tar.gz
            chdir=${js_deps} 
            creates=${js_deps}/mysql-connector-c++-1.1.1-linux-glibc2.3-x86-64bit
#install mysql cpp connector system wide
  - name: Install mysql cpp conn include
    command: cp -r ${js_deps}/mysql-connector-c++-1.1.1-linux-glibc2.3-x86-64bit/include /usr/ 
            creates=/usr/include/cppconn/ 
  - name: Install mysql cpp conn lib
    shell: cp -r ${js_deps}/mysql-connector-c++-1.1.1-linux-glibc2.3-x86-64bit/lib/* /usr/lib64/
            creates=/usr/lib64/libmysqlcppconn.so.6.1.1.1
  - name: set tmp dir perms #needed for mysql
    file: path=/tmp state=directory mode=0777
#  - name: start mysql
#    service: name=mysqld.service state=started
#  - name: create mysql db test_cube
#    mysql_db: name=test_cube state=present login_user=root login_password=""
#protobufs
  - name: make sure protobufs dir exists
    file: dest=${js_deps}/protobufs state=directory mode=777
  - name: download protobufs
    get_url: url=http://archive.ubuntu.com/ubuntu/pool/main/p/protobuf/protobuf_2.4.1.orig.tar.gz
              dest=${js_deps}/protobuf_2.4.1.orig.tar.gz
  - name: untar protobufs
    command: tar -xzf protobuf_2.4.1.orig.tar.gz
            chdir=${js_deps} 
            creates=${js_deps}/protobuf-2.4.1
  - name: configure protobuf
    command: ./configure --prefix=${js_deps}/protobufs
            chdir=${js_deps}/protobuf-2.4.1
            creates=${js_deps}/protobuf-2.4.1/config.h
  - name: make protobuf
    command: make install
            chdir=${js_deps}/protobuf-2.4.1
            creates=${js_deps}/protobufs/include
  - name: install python protobuf
    command: python setup.py install
            chdir=${js_deps}/protobuf-2.4.1/python
#js
  - name: make sure jetstream dir exists
    file: dest=${js_checkout} state=directory mode=777
  - name: make sure jetstream results dir exists
    file: dest=${js_results} state=directory mode=777
  - name: copy deploy key
    copy: src=deploy_key dest=/root/.ssh/id_rsa mode=0700
  - name: copy deploy key.pub
    copy: src=deploy_key.pub dest=/root/.ssh/id_rsa.pub mode=0700
  - name: copy known host
    copy: src=known_hosts dest=/root/.ssh/known_hosts mode=0700


